config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :tweets, only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
end

app/models/tweet.rb
class Tweet < ApplicationRecord
   belongs_to :user
   default_scope -> { order(created_at: :desc) }
   validates :user_id, presence: true
   validates :content, presence: true, length: {maximum: 100}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tweets, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  default_scope -> {order(created_at: :desc)}
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: {case_sensitive: false}
  validates :phoneNo, presence: true, length: {maximum: 12}
 
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  private
  def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    before_action :logged_in_user
    def create
        @user = User.find(params[:followed_id])
        current_user.follow(@user)
        respond_to do |format|
        format.html { redirect_to @user }
        format.js
    end
    end

    def destroy
        @user = Relationship.find(params[:id]).followed
        current_user.unfollow(@user)
        respond_to do |format|
        format.html { redirect_to @user }
        format.js
    end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = "Invalid Password or Email address"
    render 'new'
    end
  end
  def destroy
    log_out
    redirect_to root_url
  end
  
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @tweet = current_user.tweets.build if logged_in?
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :logged_in_user, only: [:create, :destroy]
    before_action :correct_user,   only: :destroy
    def create
       @tweet = current_user.tweets.build(tweet_params)
       if @tweet.save
       flash[:success] = "Tweet created!"
       redirect_to root_url
       else
       render 'static_pages/home'
       end
    end
    def destroy
    @tweet.destroy
    flash[:success] = "Tweet deleted"
    redirect_to request.referrer || root_url
    end
    private
    def tweet_params
        params.require(:tweet).permit(:content)
    end
    def correct_user
      @tweet = current_user.tweets.find_by(id: params[:id])
      redirect_to root_url if @tweet.nil?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :following, :followers]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_users, only: :destroy
  def new
    @user = User.new
  end
  def index
    @user = User.all
  end
  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets.paginate(page: params[:page])
  end
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome Friend!"
      redirect_to @user
    else
      render 'new'
    end
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile Updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  def admin_users
    redirect_to(root_url) unless current_user.admin?
  end
  
  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :phoneNo, :password, :password_confirmation, :admin)
  end
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User Deleted"
    redirect_to users_url
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    def current_user?(user)
        user == current_user
    end
    def logged_in?
        !current_user.nil?
    end
    def is_logged_in?
        !session[:user_id].nil?
    end
    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "WebPage", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
            
            <% if logged_in? %>
                  <li><%= link_to "Users", users_path %></li>
                  <li class = "dropdown">
                        <a href = "#" class = "dropdown-toggle" data-toggle = "dropdown">
                              Account <b class = "caret"></b>
                        </a>
                        <ul class = "dropdown-menu">
                              <li><%= link_to "Profile", current_user %></li>
                              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                              <li class = "divider"></li>
                              <li><%= link_to "logout", logout_path, method: :delete %></li>
                        </ul>
                  </li>
                  <% else %>
                  <li><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | HI THERE</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <div class="container">
      <% flash.each do |m_type, m| %>
      <div class = "alert alert-<%= m_type %>"></div> <%= m %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id = "error_explanation">
        <div class = "alert alert-danger">
            The form contains <%= pluralize(object.errors.count, "error") %> 
        </div>
        <ul>
            <%= object.errors.full_messages.each do |m| %>
            <li>
                <%= m %>
            </li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_tweet_form.html.erb
<%= form_for(@tweet) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new tweet..." %>
  </div>
  <%= f.submit "Tweet", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.tweets.count, "tweet") %></span>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="tweet_form">
        <%= render 'shared/tweet_form' %>
      </section>
    </aside>
  </div>
<% else %>
<div class="center jumbotron">
  <h1>Welcome to our Site!</h1>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<% end %>

app/views/tweets/_tweet.html.erb
<li id="tweet-<%= tweet.id %>">
  <span class="user"><%= link_to tweet.user.name, tweet.user %></span>
  <span class="content"><%= tweet.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(tweet.created_at) %> ago.
    <% if current_user?(tweet.user) %>
    <%= link_to "delete", tweet, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: @user %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.label :phoneNo %>
      <%= f.text_field :phoneNo, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      
      <%= f.label :admin, "Admin" %>
      <%= f.text_field :admin, class: 'form-control'%>
      
      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    <% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },  remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
</li>

app/views/users/edit.html.erb
<%provide(:title, 'Update Account') %>
<% provide(:button_text, 'Update') %>
<h1>Update</h1>
<div class = "row">
    <div class = "col-md-6 col-md-offset-3">
        <%= render 'form' %>
    </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<h1>All Users</h1>
<ul class = "users">
    <% @user.each do |user| %>
    <li>
        <%= link_to user.name, user %>
         <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
    </li>
    <% end %>
</ul>

app/views/users/new.html.erb
<%provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my Account') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
  <h1><%= @user.name %></h1>
  <h2><%= @user.email %></h2>
  <h3><%= @user.phoneNo %></h3>
  <section class="stats">
      <%= render 'shared/stats' %>
    </section>
<div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.tweets.any? %>
      <h3>Tweets</h3>
      <ol class="tweets">
        <%= render @tweets %>
      </ol>
      <%= will_paginate @tweets %>
    <% end %>
  </div>   

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      
      <h1><%= @user.name %></h1>
      <span><%= link_to "View my profile", @user %></span>
      <span><b>Tweets:</b> <%= @user.tweets.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      
        
    </section>
  </aside>
  <div class="col-md-8">
    <h2><%= @title %></h2>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>